name: Delta Award Scraper

on:
  schedule:
    - cron: '0 12 * * *'  # Every day at 12:00 UTC
  workflow_dispatch:      # Allow manual runs

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install
          npx playwright install --with-deps

      - name: Run scraper
        run: node index.js
